  
  # Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Software Carpentry at Swinburne
tagline:          'Resources from the two-day Python/Unix website'
description:      'Workshop resources for Swinburne researchers. Made by <a href="https://twitter.com/drarnakarick" target="_blank">@drarnakarick</a>.'
url:              https://github.com/drarnakarick/software-carpentry-resources
baseurl:          /software-carpentry-resources/

author:
  name:           'Arna Karick'
  url:            https://twitter.com/drarnakarick

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/drarnakarick/software-carpentry-resources
